package view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ConexionBD;
import model.Datos;

/**
 *
 * @author karen
 */
public class Abrir extends javax.swing.JFrame {

    int ID;
    String Diag_D, Diag_I;
    Float Angulo_D, Angulo_I;
    BufferedImage pieDerecho, pieIzquierdo;
    ImageIcon icon_I, icon_D;

    public Abrir() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon iconLogo = new ImageIcon("imagenes/fondo.png");
        Icon iconoP = new ImageIcon(iconLogo.getImage().getScaledInstance(307, 361, Image.SCALE_DEFAULT));
        lblimgDerecho.setIcon(iconoP);
        lblimgIzquierdo.setIcon(iconoP);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensaje = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        IdPaciente = new javax.swing.JTextField();
        lblimgIzquierdo = new javax.swing.JLabel();
        lblimgDerecho = new javax.swing.JLabel();
        lblDiagnosticoIzq = new javax.swing.JLabel();
        lblDiagnosticoDer = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMensaje.setText("Ingrese el ID del paciente a buscar");

        lblID.setText("ID del paciente: ");

        IdPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdPacienteActionPerformed(evt);
            }
        });

        lblDiagnosticoIzq.setText("Diagnostico");

        lblDiagnosticoDer.setText("Diagnostico");

        btn_regresar.setText("Listo");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblID)
                .addGap(18, 18, 18)
                .addComponent(IdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_buscar)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(lblMensaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblimgIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblDiagnosticoIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiagnosticoDer, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblimgDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btn_regresar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(IdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblimgIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(lblimgDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiagnosticoDer, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(lblDiagnosticoIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_regresar)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPacienteActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        //obtener dato del ID
        ID = Integer.parseInt(IdPaciente.getText());
        Datos e = ConexionBD.buscar(ID);
        if (e.getID() == 0) {
            JOptionPane.showMessageDialog(null, "No se tiene registro con ese ID");
        } else {
            Asignar(e);
            Colocar();
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void Asignar(Datos e) {
        Diag_D = e.getD_derecho();
        Diag_I = e.getD_izquierdo();
        Angulo_D = e.getR_pieDerecho();
        Angulo_I = e.getR_pieIzquierdo();
        icon_D = new ImageIcon(e.getUrlDerecho());
        icon_I = new ImageIcon(e.getUrlIzquierdo());

    }

    private void Colocar() {
        Icon iconoD = new ImageIcon(icon_D.getImage().getScaledInstance(307, 361, Image.SCALE_DEFAULT));
        lblimgDerecho.setIcon(iconoD);
        Icon iconoI = new ImageIcon(icon_I.getImage().getScaledInstance(307, 361, Image.SCALE_DEFAULT));
        lblimgIzquierdo.setIcon(iconoI);

        lblDiagnosticoDer.setText("Diagnostico: " + Diag_D + "Angulo Clarke: " + Math.round(Angulo_D));
        lblDiagnosticoIzq.setText("Diagnostico: " + Diag_I + "Angulo Clarke: " + Math.round(Angulo_I));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdPaciente;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel lblDiagnosticoDer;
    private javax.swing.JLabel lblDiagnosticoIzq;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblimgDerecho;
    private javax.swing.JLabel lblimgIzquierdo;
    // End of variables declaration//GEN-END:variables

}
